### ISSUE TITLE
win7/kodi poprawka trzeba

### ISSUE THREAD

**Issue by xxcriticxx** [neopack1/KODI_WTYCZKI#1]
da sie rade naprawic

wtyczka.telewizja.polska-3.1.1.zip

add on doesn't have the correct structure

wtyczka.telewizja.polska-3.1.0

dependencies not met please contact add-on author

**Comment by neopack1** [comment]
Wtyczka działa
czytaj forum mods-kodi.pl/forum/viewthread.php?thread_id=841

**Comment by xxcriticxx** [comment]
wiem ze dziala bo mam na androdzie ale na windows7 nie moge zamontowac wyskakuja takie blendy jak w pierwszym poscie

**Comment by neopack1** [comment]
bo wtyczkę należy instalować z repozytorium a nie z tego pliku zip

**Comment by xxcriticxx** [comment]
z repository sie automatycznie nie updatetujie pokazujie zeby sciagnac najnowsza ver 3.1.1.

sprobuje z tvnplayer wieczorem sie odezwe

**Comment by neopack1** [comment]
skoro tak Ci pokazuje to znaczy że masz 3.1.0 albo 3.0.9
opróżnij folder %appdata%\kodi\addons\packages
usuń folder %appdata%\kodi\addons\wtyczka.telewizja.polska
i zainstaluj z repo

**Comment by xxcriticxx** [comment]
repository.novak-3.0.2.zip

add on doesn't have the correct structure

script.module.tvnplayer-1.0.0.zip

add on doesn't have the correct structure

skasowalem wszystko z %appdata%\kodi\addons\packages
folder %appdata%\kodi\addons\wtyczka.telewizja.polska nie bylo wogole bo plugin nie zamontowany
motowalem z repository.novak-3.0.2.zip add on doesn't have the correct structure

**Comment by neopack1** [comment]
Nie mam pojęcia co jest grane... może masz jakiś problem z kodi, dziś wypuściłem update v3.1.2 i na wszystkich sprzętach działa (aktualizacja poszła automatycznie) specjalnie zainstalowałem kodi na tablecie żeby sprawdzić i też jest ok. może potrzebujesz nowszy program, sam nie wiem

**Comment by xxcriticxx** [comment]
jaka ver kodi masz?

wtyczka.telewizja.polska-3.1.2.zip
na win7 add on doesn't have the correct structure
na android add on doesn't have the correct structure

**Comment by neopack1** [comment]
począwszy od 15.2 a skończywszy na 17.0-aplha (nightles) ale ogólnie to 16 beta5
